"""add phone number to users

Revision ID: 982b572bac56
Revises: 9ef252276332
Create Date: 2023-01-27 06:18:59.053344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982b572bac56'
down_revision = '9ef252276332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
